version: '3'

services:
  postgres_db:
    image: postgres:14-alpine
    volumes:
      - telegram_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: telegram_db
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "docker_app" ]
      interval: 5s
      timeout: 5s
      retries: 3

  telegram_bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      DB_URL: jdbc:postgresql://postgres_db:5432/telegram_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      TELEGRAM_TOKEN:
      TELEGRAM_USERNAME:
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  telegram_volume: